analyzer:
  enable-experiment:
    - non-nullable
  strong-mode:
    implicit-casts: false
  exclude:
    - example/sqlite/**
    - example/webserver/**
linter:
  rules:
    lines_longer_than_80_chars
    - avoid_empty_else
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - only_throw_errors
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_getters_setters
    - package_names