analyzer:
  enable-experiment:
    - non-nullable
  strong-mode:
    implicit-casts: false
  exclude:
    - example/**
linter:
  rules:
    - avoid_empty_else
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - avoid_slow_async_io
    - cancel_subscriptions
    - test_types_in_equals
    - throw_in_finally
    - valid_regexps
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - constant_identifier_names
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - only_throw_errors
    - package_api_docs
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - type_init_formals
    - unnecessary_getters_setters
    - package_names
    - unnecessary_await_in_return
    - use_function_type_syntax_for_parameters
    - avoid_returning_null_for_future
    - no_duplicate_case_values
    - unnecessary_statements
    - always_require_non_null_named_parameters
    - always_put_required_named_parameters_first
    - avoid_catches_without_on_clauses
    - avoid_function_literals_in_foreach_calls
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_returning_null_for_void
    - avoid_returning_this
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - empty_catches
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - null_closures
    - omit_local_variable_types
    - one_member_abstracts
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_double_quotes
    - prefer_equal_for_default_values
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - provide_deprecation_message
    - prefer_typing_uninitialized_variables
    - public_member_api_docs
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_lambdas
    - unnecessary_null_in_if_null_operators
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_string_escapes
    - use_rethrow_when_possible
    - use_string_buffers
    - void_checks
    - use_to_and_as_if_applicable
    - sort_pub_dependencies
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_spread_collections